-d C:\Users\Mr T\Desktop\TangNano20K_Test\impl\gwsynthesis\picorv32_20k.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\Mr T\Desktop\TangNano20K_Test\src\picorv32_20k.cst
-cfg C:\Users\Mr T\Desktop\TangNano20K_Test\impl\pnr\device.cfg
-sdc C:\Users\Mr T\Desktop\TangNano20K_Test\src\picorv32_20k.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
